export class ClasseIrradiacao {
  "ID":number,
    "COUNTRY":string,
    "LON":number,
    "LAT":number,
    "ANNUAL":number,
    "JAN":number,
    "FEB":number,
    "MAR":number,
    "APR":number,
    "MAY":number,
    "JUN":number,
    "JUL":number,
    "AUG":number,
    "SEP":number,
    "OCT":number,
    "NOV":number,
    "DEC":number
}
